
// C++ header file "GrphaicDirectX9.h" for class GrphaicDirectX9 generated by Poseidon for UML.
// Poseidon for UML is developed by Gentleware (http://www.gentleware.com).
// Generated with velocity template engine (http://jakarta.apache.org/velocity).

#ifndef GrphaicDirectX9_Im5fa52b0cm122a159526cmm7e5f_H
#define GrphaicDirectX9_Im5fa52b0cm122a159526cmm7e5f_H

#define DIRECTINPUT_VERSION 0x0800
#include <d3d9.h>
#include <d3dx9.h>

#pragma comment(lib, "d3d9.lib")
#pragma comment(lib, "d3dx9.lib")

#define SAFE_RELEASE(x) if (x) { x->Release(); x=NULL; }
#define RELEASE_ARRAY(x) if (x) { delete [] x; x=NULL; }

class GrphaicDirectX9 
{
public:
	GrphaicDirectX9(HWND hWnd);
	~GrphaicDirectX9(void);
	bool InitDevice();
	bool ResetDevice(void);
	bool ReleaseGraphicsDevice(void);
	LPDIRECT3DDEVICE9 GetGraphicsDevice(void);
	LPDIRECT3D9 GetD3D9(void);
	LPDIRECT3DVERTEXSHADER9 LoadVertexShader_HLSL(const wchar_t *fullpath, const char *entry, const char *profile);
	LPDIRECT3DPIXELSHADER9 LoadPixelShader_HLSL(const wchar_t *fullpath, const char *entry, const char *profile);
	LPDIRECT3DVERTEXSHADER9 LoadVertexShader_ASM(const wchar_t *fullpath);
	LPDIRECT3DPIXELSHADER9 LoadPixelShader_ASM(const wchar_t *fullpath);
	LPD3DXEFFECT LoadFXShader(const wchar_t *filename);
private:
	LPDIRECT3D9 m_pD3D;
	LPDIRECT3DDEVICE9 m_pD3DDevice;
	D3DPRESENT_PARAMETERS m_pD3DPresent;
	HWND m_hWnd;
};

#endif // GrphaicDirectX9_Im5fa52b0cm122a159526cmm7e5f_H

