
// C++ header file "Win32Window.h" for class Win32Window generated by Poseidon for UML.
// Poseidon for UML is developed by Gentleware (http://www.gentleware.com).
// Generated with velocity template engine (http://jakarta.apache.org/velocity).

#ifndef Win32Window_Im40eda407m1229c278a93mm7e5f_H
#define Win32Window_Im40eda407m1229c278a93mm7e5f_H

// Windows º–¿Y¿…:
#include <windows.h>

class Win32Window 
{	
public:
	Win32Window(void);
	HWND	ToCreateWindow(int x, int y, int width, int height, const wchar_t *title,  LRESULT (_stdcall *wndporc)(HWND, UINT, WPARAM, LPARAM) = &Win32Window::Proc);
	MSG	HandlePeekMessage(void);
	HWND	GetHandle(void);
	HINSTANCE	GetInstance(void);
	RECT	GetRect(void);
	void	GetMouseState(int &x, int &y, int button[3]);
	void	ToShow(void);
	void	ToHide(void);
	void	ToMove(UINT x, UINT y, UINT nWidth, UINT nHeight, bool bRepaint = true);
	
	static LRESULT CALLBACK Proc(HWND hWnd, UINT message, WPARAM wParam, LPARAM lParam)
	{
		switch (message)
		{
		case WM_DESTROY:
			PostQuitMessage(0);
			break;
		default:
			return DefWindowProc(hWnd, message, wParam, lParam);
		}
		return 0;
	}
private:
	HWND m_hWnd;
	HINSTANCE m_hInstance;
};


#endif // Win32Window_Im40eda407m1229c278a93mm7e5f_H

